services:
  lab:
    build:
      context: .
    container_name: privesc_lab
    hostname: privesc-lab
    environment:
      TERM: xterm-256color
    stdin_open: true
    tty: true
    restart: unless-stopped
    image: am-i-root-now-lab:latest
